// src/widgets/common/FluentSelect.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";

interface FluentSelectOption<T extends string | number> {
  label: string;
  value: T | "";
}

interface FluentSelectProps<T extends string | number> {
  modelValue: T | "";
  options: Array<FluentSelectOption<T>>;
  placeholder?: string;
  disabled?: boolean;
  searchable?: boolean;
  size?: "sm" | "md" | "lg";
  className?: string;
  onUpdateModelValue?: (value: T | "") => void;
  onChange?: (value: T | "") => void;
}

export default function FluentSelect<T extends string | number>({
  modelValue,
  options,
  placeholder = "请选择",
  disabled = false,
  searchable = false,
  size = "md",
  className = "",
  onUpdateModelValue,
  onChange,
}: FluentSelectProps<T>) {
  const [isOpen, setIsOpen] = useState(false);
  const [searchKeyword, setSearchKeyword] = useState("");
  const [highlightIndex, setHighlightIndex] = useState(-1);
  const [menuStyle, setMenuStyle] = useState<{ top: string; left: string; width: string }>({
    top: "0px",
    left: "0px",
    width: "auto",
  });
  const comboRef = useRef<HTMLDivElement | null>(null);
  const triggerRef = useRef<HTMLDivElement | null>(null);
  const menuRef = useRef<HTMLDivElement | null>(null);
  const searchInputRef = useRef<HTMLInputElement | null>(null);

  const filteredOptions = useMemo(() => {
    if (!searchable || !searchKeyword.trim()) {
      return options;
    }
    const keyword = searchKeyword.trim().toLowerCase();
    return options.filter((option) => option.label.toLowerCase().includes(keyword));
  }, [options, searchKeyword, searchable]);

  const displayLabel = useMemo(() => {
    if (modelValue === "" || modelValue === null || modelValue === undefined) {
      const defaultPlaceholderOption = options.find((option) => option.value === "");
      return defaultPlaceholderOption ? defaultPlaceholderOption.label : placeholder;
    }
    const selected = options.find((option) => option.value === modelValue);
    return selected ? selected.label : placeholder;
  }, [modelValue, options, placeholder]);

  const isPlaceholder = useMemo(() => {
    if (modelValue === "" || modelValue === null || modelValue === undefined) {
      return !options.find((option) => option.value === "");
    }
    return false;
  }, [modelValue, options]);

  useEffect(() => {
    if (searchable && modelValue !== "" && modelValue !== null && modelValue !== undefined) {
      const selected = options.find((option) => option.value === modelValue);
      if (selected) {
        setSearchKeyword(selected.label);
      }
      return;
    }
    if (searchable) {
      setSearchKeyword("");
    }
  }, [modelValue, options, searchable]);

  useEffect(() => {
    if (!isOpen) {
      setHighlightIndex(-1);
      if (!searchable) {
        setSearchKeyword("");
      }
      return;
    }

    function handleScrollOrResize(event: Event) {
      if (event.type === "scroll" && event.target === menuRef.current) {
        return;
      }
      setIsOpen(false);
    }

    function handleClickOutside(event: MouseEvent) {
      const target = event.target as Node;
      if (comboRef.current?.contains(target) || menuRef.current?.contains(target)) {
        return;
      }
      setIsOpen(false);
    }

    window.addEventListener("scroll", handleScrollOrResize, true);
    window.addEventListener("resize", handleScrollOrResize);
    document.addEventListener("mousedown", handleClickOutside);

    return () => {
      window.removeEventListener("scroll", handleScrollOrResize, true);
      window.removeEventListener("resize", handleScrollOrResize);
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [isOpen, searchable]);

  function updatePosition() {
    if (!triggerRef.current) {
      return;
    }
    const rect = triggerRef.current.getBoundingClientRect();
    const viewportHeight = window.innerHeight;
    const spaceBelow = viewportHeight - rect.bottom;
    const spaceAbove = rect.top;
    const estimatedHeight = Math.min(240, Math.max(spaceBelow, spaceAbove) - 12);

    setMenuStyle({
      top: spaceBelow < 240 && spaceAbove > spaceBelow
        ? `${rect.top - estimatedHeight - 6}px`
        : `${rect.bottom + 6}px`,
      left: `${rect.left}px`,
      width: `${rect.width}px`,
    });
  }

  function openCombo() {
    if (disabled || isOpen) {
      return;
    }
    updatePosition();
    setHighlightIndex(-1);
    setIsOpen(true);
    if (searchable) {
      window.setTimeout(() => {
        const input = searchInputRef.current;
        if (!input) {
          return;
        }
        input.focus();
        const len = input.value.length;
        input.setSelectionRange(len, len);
      }, 0);
    } else {
      comboRef.current?.focus();
    }
  }

  function closeCombo() {
    setIsOpen(false);
  }

  function toggleCombo() {
    if (disabled) {
      return;
    }
    if (isOpen) {
      closeCombo();
    } else {
      openCombo();
    }
  }

  function selectOption(value: T | "") {
    if (disabled) {
      return;
    }
    if (searchable) {
      const selected = options.find((option) => option.value === value);
      setSearchKeyword(selected ? selected.label : "");
    }
    onUpdateModelValue?.(value);
    onChange?.(value);
    closeCombo();
  }

  function scrollHighlightedIntoView() {
    window.setTimeout(() => {
      const highlighted = menuRef.current?.querySelector(".fluent-option.highlighted") as HTMLElement | null;
      highlighted?.scrollIntoView({ block: "nearest" });
    }, 0);
  }

  function navigateOptions(direction: number) {
    const len = filteredOptions.length;
    if (len === 0) {
      return;
    }
    setHighlightIndex((current) => {
      const next = current === -1 ? (direction > 0 ? 0 : len - 1) : (current + direction + len) % len;
      window.setTimeout(scrollHighlightedIntoView, 0);
      return next;
    });
  }

  function selectHighlighted() {
    if (highlightIndex >= 0 && highlightIndex < filteredOptions.length) {
      selectOption(filteredOptions[highlightIndex].value);
    }
  }

  const comboClasses = `fluent-combo ${isOpen ? "open" : ""} ${disabled ? "disabled" : ""} ${size !== "md" ? `size-${size}` : ""} ${className}`.trim();

  return (
    <div
      className={comboClasses}
      tabIndex={searchable ? -1 : 0}
      onKeyDown={(event) => {
        if (event.key === "Escape") {
          event.preventDefault();
          closeCombo();
        }
      }}
      ref={comboRef}
    >
      {searchable ? (
        <div
          className="fluent-trigger fluent-searchable-trigger"
          ref={triggerRef}
          onMouseDown={(event) => {
            event.preventDefault();
            if (!isOpen) {
              openCombo();
              return;
            }
            const input = searchInputRef.current;
            if (!input) {
              return;
            }
            input.focus();
            const len = input.value.length;
            input.setSelectionRange(len, len);
          }}
        >
          <input
            ref={searchInputRef}
            className="fluent-searchable-input"
            value={searchKeyword}
            placeholder={isPlaceholder ? placeholder : ""}
            onChange={(event) => {
              setSearchKeyword(event.target.value);
              setHighlightIndex(-1);
              if (!isOpen) {
                openCombo();
              }
            }}
            onKeyDown={(event) => {
              if (event.key === "Escape") {
                event.preventDefault();
                closeCombo();
              }
              if (event.key === "ArrowDown") {
                event.preventDefault();
                event.stopPropagation();
                navigateOptions(1);
              }
              if (event.key === "ArrowUp") {
                event.preventDefault();
                event.stopPropagation();
                navigateOptions(-1);
              }
              if (event.key === "Enter") {
                event.preventDefault();
                event.stopPropagation();
                selectHighlighted();
              }
            }}
          />
          <span className="material-symbols-rounded combo-icon" aria-hidden="true">keyboard_arrow_down</span>
        </div>
      ) : (
        <div className="fluent-trigger" ref={triggerRef} onMouseDown={(event) => {
          event.preventDefault();
          toggleCombo();
        }}>
          <span className={`fluent-value ${isPlaceholder ? "placeholder" : ""}`.trim()}>
            {displayLabel}
          </span>
          <span className="material-symbols-rounded combo-icon" aria-hidden="true">keyboard_arrow_down</span>
        </div>
      )}

      {createPortal(
        isOpen ? (
          <div className="teleported-fluent-menu" style={menuStyle} ref={menuRef}>
            {filteredOptions.map((option, index) => (
              <button
                key={String(option.value)}
                type="button"
                className={`fluent-option ${option.value === modelValue ? "selected" : ""} ${index === highlightIndex ? "highlighted" : ""}`.trim()}
                onClick={() => selectOption(option.value)}
              >
                {option.label}
              </button>
            ))}
            {filteredOptions.length === 0 ? (
              <div className="menu-empty">无匹配选项</div>
            ) : null}
          </div>
        ) : null,
        document.body,
      )}
    </div>
  );
}

// src/widgets/common/FluentSelect.vue
<template>
  <div
    class="fluent-combo"
    :class="{ open: isOpen, disabled }"
    :tabindex="searchable ? -1 : 0"
    @keydown.esc.prevent="closeCombo"
    ref="comboRef"
  >
    <template v-if="searchable">
      <div class="fluent-trigger fluent-searchable-trigger" ref="triggerRef" @mousedown.prevent="onSearchTriggerMouseDown">
        <input
          ref="searchInputRef"
          class="fluent-searchable-input"
          :value="searchKeyword"
          :placeholder="isPlaceholder ? placeholder : ''"
          @input="handleSearchInput"
          @keydown.esc.prevent="closeCombo"
          @keydown.down.prevent.stop="navigateOptions(1)"
          @keydown.up.prevent.stop="navigateOptions(-1)"
          @keydown.enter.prevent.stop="selectHighlighted"
        />
        <span class="material-symbols-rounded combo-icon">keyboard_arrow_down</span>
      </div>
    </template>
    <template v-else>
      <div class="fluent-trigger" ref="triggerRef" @mousedown.prevent="toggleCombo">
        <span class="fluent-value" :class="{ placeholder: isPlaceholder }">
          {{ displayLabel }}
        </span>
        <span class="material-symbols-rounded combo-icon">keyboard_arrow_down</span>
      </div>
    </template>

    <Teleport to="body">
      <div
        v-show="isOpen"
        class="teleported-fluent-menu"
        :style="menuStyle"
        ref="menuRef"
      >
        <button
          v-for="(opt, idx) in filteredOptions"
          :key="opt.value"
          type="button"
          class="fluent-option"
          :class="{ selected: opt.value === modelValue, highlighted: idx === highlightIndex }"
          @click="selectOption(opt.value)"
        >
          {{ opt.label }}
        </button>
        <div v-if="filteredOptions.length === 0" class="menu-empty">无匹配选项</div>
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts" generic="T extends string | number">
import { computed, ref, reactive, onUnmounted, watch, nextTick } from "vue";

const props = withDefaults(
  defineProps<{
    modelValue: T | "";
    options: { label: string; value: T | "" }[];
    placeholder?: string;
    disabled?: boolean;
    searchable?: boolean;
  }>(),
  {
    placeholder: "请选择",
    disabled: false,
    searchable: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: T | ""];
  "change": [value: T | ""];
}>();

const isOpen = ref(false);
const comboRef = ref<HTMLElement | null>(null);
const triggerRef = ref<HTMLElement | null>(null);
const menuRef = ref<HTMLElement | null>(null);
const searchInputRef = ref<HTMLInputElement | null>(null);
const searchKeyword = ref("");
const highlightIndex = ref(-1);

const menuStyle = reactive({
  top: "0px",
  left: "0px",
  width: "auto",
});

const filteredOptions = computed(() => {
  if (!props.searchable || !searchKeyword.value.trim()) {
    return props.options;
  }
  const kw = searchKeyword.value.trim().toLowerCase();
  return props.options.filter((opt) => opt.label.toLowerCase().includes(kw));
});

const displayLabel = computed(() => {
  if (props.modelValue === "" || props.modelValue === null || props.modelValue === undefined) {
    const defaultPlaceholderOption = props.options.find((opt) => opt.value === "");
    return defaultPlaceholderOption ? defaultPlaceholderOption.label : props.placeholder;
  }
  const found = props.options.find((opt) => opt.value === props.modelValue);
  return found ? found.label : props.placeholder;
});

const isPlaceholder = computed(() => {
  if (props.modelValue === "" || props.modelValue === null || props.modelValue === undefined) {
    const defaultPlaceholderOption = props.options.find((opt) => opt.value === "");
    return !defaultPlaceholderOption;
  }
  return false;
});

function updatePosition() {
  if (!triggerRef.value) return;
  const rect = triggerRef.value.getBoundingClientRect();

  const viewportHeight = window.innerHeight;
  const spaceBelow = viewportHeight - rect.bottom;
  const spaceAbove = rect.top;
  const estimatedHeight = Math.min(240, Math.max(spaceBelow, spaceAbove) - 12);

  if (spaceBelow < 240 && spaceAbove > spaceBelow) {
    menuStyle.top = `${rect.top - estimatedHeight - 6}px`;
  } else {
    menuStyle.top = `${rect.bottom + 6}px`;
  }

  menuStyle.left = `${rect.left}px`;
  menuStyle.width = `${rect.width}px`;
}

function handleScrollOrResize(e: Event) {
  if (!isOpen.value) return;
  if (e.type === "scroll" && e.target === menuRef.value) {
    return;
  }
  closeCombo();
}

function handleClickOutside(e: MouseEvent) {
  if (!isOpen.value) return;
  const target = e.target as Node;
  if (comboRef.value?.contains(target) || menuRef.value?.contains(target)) {
    return;
  }
  closeCombo();
}

function openCombo() {
  if (props.disabled) return;
  if (isOpen.value) return;
  highlightIndex.value = -1;
  updatePosition();
  isOpen.value = true;
  window.addEventListener("scroll", handleScrollOrResize, true);
  window.addEventListener("resize", handleScrollOrResize);
  document.addEventListener("mousedown", handleClickOutside);
  if (props.searchable) {
    nextTick(() => {
      nextTick(() => {
        const input = searchInputRef.value;
        if (!input) return;
        input.focus();
        const len = input.value.length;
        input.setSelectionRange(len, len);
      });
    });
  } else {
    comboRef.value?.focus();
  }
}

function onSearchTriggerMouseDown() {
  if (props.disabled) return;
  if (!isOpen.value) {
    openCombo();
  } else {
    const input = searchInputRef.value;
    if (!input) return;
    input.focus();
    const len = input.value.length;
    input.setSelectionRange(len, len);
  }
}

function toggleCombo() {
  if (props.disabled) return;
  if (isOpen.value) {
    closeCombo();
  } else {
    openCombo();
  }
}

function closeCombo() {
  isOpen.value = false;
  if (!props.searchable) {
    searchKeyword.value = "";
  }
  highlightIndex.value = -1;
  window.removeEventListener("scroll", handleScrollOrResize, true);
  window.removeEventListener("resize", handleScrollOrResize);
  document.removeEventListener("mousedown", handleClickOutside);
  comboRef.value?.blur();
}

function selectOption(value: T | "") {
  if (props.disabled) return;
  if (props.searchable) {
    const selected = props.options.find((opt) => opt.value === value);
    searchKeyword.value = selected ? selected.label : "";
  }
  emit("update:modelValue", value);
  emit("change", value);
  closeCombo();
}

function handleSearchInput(e: Event) {
  searchKeyword.value = (e.target as HTMLInputElement).value;
  highlightIndex.value = -1;
  if (!isOpen.value) {
    openCombo();
  }
}

function navigateOptions(direction: number) {
  const len = filteredOptions.value.length;
  if (len === 0) return;
  if (highlightIndex.value === -1) {
    highlightIndex.value = direction > 0 ? 0 : len - 1;
  } else {
    highlightIndex.value = (highlightIndex.value + direction + len) % len;
  }
  scrollHighlightedIntoView();
}

function selectHighlighted() {
  if (highlightIndex.value >= 0 && highlightIndex.value < filteredOptions.value.length) {
    selectOption(filteredOptions.value[highlightIndex.value].value);
  }
}

function scrollHighlightedIntoView() {
  nextTick(() => {
    const menu = menuRef.value;
    if (!menu) return;
    const highlighted = menu.querySelector(".fluent-option.highlighted") as HTMLElement;
    if (highlighted) {
      highlighted.scrollIntoView({ block: "nearest" });
    }
  });
}

watch(() => isOpen.value, (val) => {
  if (!val) {
    if (!props.searchable) {
      searchKeyword.value = "";
    }
    highlightIndex.value = -1;
  }
});

watch(() => props.modelValue, (val) => {
  if (props.searchable && (val === "" || val === null || val === undefined)) {
    searchKeyword.value = "";
    return;
  }
  if (props.searchable && val !== "") {
    const selected = props.options.find((opt) => opt.value === val);
    if (selected) {
      searchKeyword.value = selected.label;
    }
  }
}, { immediate: true });

onUnmounted(() => {
  window.removeEventListener("scroll", handleScrollOrResize, true);
  window.removeEventListener("resize", handleScrollOrResize);
  document.removeEventListener("mousedown", handleClickOutside);
});
</script>

<style scoped>
.fluent-combo {
  position: relative;
  display: flex;
  outline: none;
  min-width: 120px;
}

.fluent-trigger {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  min-height: 38px;
  padding: 0 32px 0 var(--space-md);
  border-radius: var(--radius-sm);
  border: 1px solid var(--border-default);
  background: var(--surface-input);
  cursor: pointer;
  font-size: var(--font-size-base);
  color: var(--text-primary);
  transition:
    border-color var(--transition-base) var(--transition-ease),
    box-shadow var(--transition-base) var(--transition-ease);
}

.fluent-searchable-trigger {
  cursor: text;
}

.fluent-searchable-input {
  flex: 1;
  border: 0;
  background: transparent;
  outline: none;
  font-size: var(--font-size-base);
  color: var(--text-primary);
  font-family: var(--font-ui);
  width: 100%;
  min-height: 38px;
}

.fluent-searchable-input::placeholder {
  color: var(--text-tertiary);
}

.fluent-value {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.fluent-value.placeholder {
  color: var(--text-tertiary);
}

.combo-icon {
  position: absolute;
  right: 10px;
  top: 50%;
  transform: translateY(-50%);
  font-size: 18px;
  color: var(--text-tertiary);
  pointer-events: none;
  transition: transform var(--transition-base) var(--transition-ease);
}

.fluent-combo.open .combo-icon {
  transform: translateY(-50%) rotate(180deg);
}

.fluent-combo:focus-within .fluent-trigger,
.fluent-combo.open .fluent-trigger {
  border-color: rgba(var(--accent-rgb), 0.5);
  box-shadow: 0 0 0 3px var(--accent-focus-ring);
}

.fluent-combo.disabled .fluent-trigger {
  opacity: 0.5;
  cursor: not-allowed;
  background: var(--surface-elevated);
}
</style>

<style>
.teleported-fluent-menu {
  position: fixed;
  max-height: 240px;
  padding: 4px;
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
  background: var(--surface-panel);
  box-shadow: var(--shadow-strong);
  overflow-y: auto;
  z-index: 99999;
  animation: menu-appear 0.12s var(--transition-ease) forwards;
  transform-origin: top;
  box-sizing: border-box;
}

@keyframes menu-appear {
  from {
    opacity: 0;
    transform: scaleY(0.96) translateY(-4px);
  }
  to {
    opacity: 1;
    transform: scaleY(1) translateY(0);
  }
}

.teleported-fluent-menu .fluent-option {
  width: 100%;
  min-height: 34px;
  border: 0;
  border-radius: var(--radius-sm);
  background: transparent;
  text-align: left;
  padding: 6px var(--space-md);
  cursor: pointer;
  font-size: var(--font-size-sm);
  color: var(--text-primary);
  transition:
    background-color var(--transition-fast) var(--transition-ease),
    color var(--transition-fast) var(--transition-ease);
  display: flex;
  align-items: center;
  box-sizing: border-box;
  font-family: var(--font-ui);
}

.teleported-fluent-menu .fluent-option:hover {
  background: var(--accent-fill-soft);
  color: var(--accent-primary);
}

.teleported-fluent-menu .fluent-option.selected {
  background: var(--accent-soft);
  color: var(--accent-primary);
  font-weight: 600;
}

.teleported-fluent-menu .fluent-option.highlighted {
  background: var(--accent-fill-soft);
}

.teleported-fluent-menu .menu-empty {
  padding: var(--space-sm) var(--space-md);
  color: var(--text-tertiary);
  font-size: var(--font-size-sm);
  text-align: center;
}
</style>
